version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - uv sync
  build:
    commands:
      - uv run pytest tests/test_cv_parser.py -v
