name: CI

# Triggers on push
on:
  push:
    branches:
    - main

jobs:
  test:

    # Start an ubuntu  instance
    runs-on: ubuntu-latest

    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Get the code from main
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup python and uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/.python-version"

      # Install dependencies
      - name: Install Deps
        run: cd backend && uv sync --all-extras --dev

      # Run the tests
      - name: Run tests
        run: cd backend && uv run pytest tests/ -v

