name: CI

# Triggers on push
on:
  push:
    branches:
    - main

jobs:
  test:

    # Start an ubuntu  instance
    runs-on: ubuntu-latest

    steps:

      # Get the code from main
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup python and uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/.python-version"

      # Install dependencies
      - name: Install Deps
        run: cd backend && uv sync --all-extras --dev

      # Run the tests
      - name: Run tests
        run: cd backend && uv run pytest tests/ -v

