name: CI

# Triggers on push
on:
  push:
    branches:
    - main

jobs:
  test:

    # Start an ubuntu  instance
    runs-on: ubuntu-latest

    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:

      # Get the code from main
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup python and uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/.python-version"

      # Install dependencies
      - name: Install Deps
        run: cd backend && uv sync --all-extras --dev

      # Setup AWS
      - name: Configure AWS CLI
        run: |
          pip install awscli
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      # Run the tests
      - name: Run tests
        run: cd backend && uv run pytest tests/ -v

