name: CI

# Triggers on push
on:
  push:
    branches:
    - main

jobs:
  test:

    # Start an ubuntu  instance
    runs-on: ubuntu-latest

    steps:

      # Get the code from main
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies

      # Install dependencies
      - name: Install Deps
        run: pip install -r requirements.txt

      # Run the tests
      - name: Run tests
        run: pytest tests/test_cv_parser.py -v

